from pathlib import Path

path = Path('components/SquadMaker.tsx')
source = path.read_text(encoding='utf-8')

old_state = '''  const [pendingPlayer, setPendingPlayer] = useState<SearchPlayer | null>(null);\n  const [pendingGrade, setPendingGrade] = useState(grade);\n  const [pendingDetails, setPendingDetails] = useState<SquadCardDetails | null>(null);\n  const [pendingDetailsLoading, setPendingDetailsLoading] = useState(false);'''
new_state = '''  const [pendingPlayer, setPendingPlayer] = useState<SearchPlayer | null>(null);\n  const [pendingGrade, setPendingGrade] = useState(grade);\n  const [pendingDetails, setPendingDetails] = useState<SquadCardDetails | null>(null);\n  const [pendingDetailsLoading, setPendingDetailsLoading] = useState(false);\n  const [resultDetails, setResultDetails] = useState<Record<number, SquadCardDetails>>({});'''
if old_state not in source:
    raise SystemExit('state insertion point not found')
source = source.replace(old_state, new_state, 1)

marker = '''  useEffect(() => {\n    if (!pendingPlayer) {\n      setPendingDetails(null);\n      setPendingDetailsLoading(false);\n      return;\n    }'''
idx = source.find(marker)
if idx < 0:
    raise SystemExit('pending effect marker not found')

result_effect = '''  useEffect(() => {\n    if (results.length === 0) {\n      setResultDetails({});\n      return;\n    }\n\n    const controller = new AbortController();\n    setResultDetails({});\n\n    const load = async () => {\n      const next: Record<number, SquadCardDetails> = {};\n      for (let index = 0; index < results.length; index += 3) {\n        const batch = results.slice(index, index + 3);\n        const loaded = await Promise.all(\n          batch.map(async (player) => {\n            try {\n              const response = await fetch(\n                `/api/squad/card?spid=${player.id}&name=${encodeURIComponent(player.name)}&position=${encodeURIComponent(slot.label)}`,\n                { signal: controller.signal }\n              );\n              if (!response.ok) return null;\n              const data = await response.json();\n              return [\n                player.id,\n                {\n                  salary: Number.isFinite(data.salary) ? data.salary : null,\n                  prices: Array.isArray(data.prices) ? data.prices : [],\n                  positionOvr: Number.isFinite(data.positionOvr) ? data.positionOvr : null,\n                } satisfies SquadCardDetails,\n              ] as const;\n            } catch {\n              return null;\n            }\n          })\n        );\n\n        if (controller.signal.aborted) return;\n        for (const item of loaded) {\n          if (item) next[item[0]] = item[1];\n        }\n        setResultDetails({ ...next });\n      }\n    };\n\n    void load();\n    return () => controller.abort();\n  }, [results, slot.label]);\n\n'''
source = source[:idx] + result_effect + source[idx:]

old_results = '''              {!loading && !error && results.map((player) => (\n                <button\n                  key={player.id}\n                  type="button"\n                  onClick={() => {\n                    setPendingPlayer(player);\n                    setPendingGrade(grade);\n                  }}\n                  className="flex w-full items-start gap-3 rounded-xl border border-white/[0.08] bg-black/10 p-3 text-left transition hover:border-lime-400/30 hover:bg-lime-400/[0.04]"\n                >\n                  <div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-lg bg-white/[0.04]">\n                    {player.seasonImg ? <img src={player.seasonImg} alt={player.seasonName} className="max-h-9 max-w-10 object-contain" /> : <span className="text-xs text-gray-700">-</span>}\n                  </div>\n                  <div className="min-w-0 flex-1">\n                    <p className="truncate text-sm font-black">{player.name}</p>\n                    <p className="mt-1 truncate text-xs text-gray-500">{player.seasonName}</p>\n                    {(player.newTraits?.length ?? 0) > 0 && <TraitChips traits={player.newTraits ?? []} compactMode />}\n                  </div>\n                  <div className="shrink-0 text-right">\n                    <p className="text-lg font-black text-lime-300">{player.ovr ?? "-"}</p>\n                    <p className="text-[10px] font-bold text-gray-500">{player.position ?? "OVR"}</p>\n                  </div>\n                </button>\n              ))}'''
new_results = '''              {!loading && !error && results.map((player) => {\n                const details = resultDetails[player.id];\n                const price = details?.prices?.[grade - 1];\n                return (\n                  <button\n                    key={player.id}\n                    type="button"\n                    onClick={() => {\n                      setPendingPlayer(player);\n                      setPendingGrade(grade);\n                    }}\n                    className="flex w-full items-center gap-3 rounded-xl border border-white/[0.08] bg-black/10 p-2.5 text-left transition hover:border-lime-400/30 hover:bg-lime-400/[0.04]"\n                  >\n                    <div className="relative h-[68px] w-[58px] shrink-0 overflow-hidden rounded-lg border border-white/10 bg-white/[0.04]">\n                      <PlayerArtwork\n                        spid={player.id}\n                        alt={`${player.name} ${player.seasonName} 액션샷`}\n                        className="absolute bottom-0 left-1/2 max-h-[64px] max-w-[135%] -translate-x-1/2 object-contain"\n                      />\n                      {player.seasonImg && (\n                        <img\n                          src={player.seasonImg}\n                          alt={player.seasonName}\n                          className="absolute bottom-1 right-1 z-10 h-4 max-w-6 object-contain"\n                        />\n                      )}\n                    </div>\n                    <div className="min-w-0 flex-1">\n                      <p className="truncate text-sm font-black">{player.name}</p>\n                      <p className="mt-0.5 truncate text-[11px] text-gray-500">{player.seasonName}</p>\n                      <p className="mt-1 truncate text-[11px] font-black text-amber-300">\n                        {details ? `${grade}강 · ${formatPlayerPrice(price)}` : `${grade}강 · 가격 불러오는 중...`}\n                      </p>\n                      {(player.newTraits?.length ?? 0) > 0 && <TraitChips traits={player.newTraits ?? []} compactMode />}\n                    </div>\n                    <div className="shrink-0 text-right">\n                      <p className="text-lg font-black text-lime-300">{player.ovr ?? "-"}</p>\n                      <p className="text-[10px] font-bold text-gray-500">{player.position ?? "OVR"}</p>\n                    </div>\n                  </button>\n                );\n              })}'''
if old_results not in source:
    raise SystemExit('results block not found')
source = source.replace(old_results, new_results, 1)

path.write_text(source, encoding='utf-8')
