create table if not exists public.community_posts (
  id uuid primary key default gen_random_uuid(),
  author_id uuid not null references auth.users(id) on delete cascade,
  category text not null default 'free',
  title text not null,
  content text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint community_posts_category_check check (category in ('free','question','tip','squad')),
  constraint community_posts_title_length check (char_length(title) between 1 and 80),
  constraint community_posts_content_length check (char_length(content) between 1 and 5000)
);

create table if not exists public.community_comments (
  id bigint generated by default as identity primary key,
  post_id uuid not null references public.community_posts(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  content text not null,
  created_at timestamptz not null default now(),
  constraint community_comments_content_length check (char_length(content) between 1 and 1000)
);

create table if not exists public.community_likes (
  post_id uuid not null references public.community_posts(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (post_id, user_id)
);

create index if not exists community_posts_created_at_idx on public.community_posts(created_at desc);
create index if not exists community_posts_category_created_at_idx on public.community_posts(category, created_at desc);
create index if not exists community_comments_post_created_at_idx on public.community_comments(post_id, created_at);
create index if not exists community_likes_post_id_idx on public.community_likes(post_id);

alter table public.community_posts enable row level security;
alter table public.community_comments enable row level security;
alter table public.community_likes enable row level security;

grant select on public.community_posts, public.community_comments, public.community_likes to anon;
grant select, insert, update, delete on public.community_posts, public.community_comments, public.community_likes to authenticated;
grant usage, select on sequence public.community_comments_id_seq to authenticated;

drop policy if exists "community_posts_public_read" on public.community_posts;
create policy "community_posts_public_read" on public.community_posts for select to anon, authenticated using (true);
drop policy if exists "community_posts_insert_own" on public.community_posts;
create policy "community_posts_insert_own" on public.community_posts for insert to authenticated with check ((select auth.uid()) = author_id);
drop policy if exists "community_posts_update_own" on public.community_posts;
create policy "community_posts_update_own" on public.community_posts for update to authenticated using ((select auth.uid()) = author_id) with check ((select auth.uid()) = author_id);
drop policy if exists "community_posts_delete_own" on public.community_posts;
create policy "community_posts_delete_own" on public.community_posts for delete to authenticated using ((select auth.uid()) = author_id);

drop policy if exists "community_comments_public_read" on public.community_comments;
create policy "community_comments_public_read" on public.community_comments for select to anon, authenticated using (true);
drop policy if exists "community_comments_insert_own" on public.community_comments;
create policy "community_comments_insert_own" on public.community_comments for insert to authenticated with check ((select auth.uid()) = user_id);
drop policy if exists "community_comments_update_own" on public.community_comments;
create policy "community_comments_update_own" on public.community_comments for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists "community_comments_delete_own" on public.community_comments;
create policy "community_comments_delete_own" on public.community_comments for delete to authenticated using ((select auth.uid()) = user_id);

drop policy if exists "community_likes_public_read" on public.community_likes;
create policy "community_likes_public_read" on public.community_likes for select to anon, authenticated using (true);
drop policy if exists "community_likes_insert_own" on public.community_likes;
create policy "community_likes_insert_own" on public.community_likes for insert to authenticated with check ((select auth.uid()) = user_id);
drop policy if exists "community_likes_delete_own" on public.community_likes;
create policy "community_likes_delete_own" on public.community_likes for delete to authenticated using ((select auth.uid()) = user_id);
