create table if not exists public.user_notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  actor_id uuid references auth.users(id) on delete set null,
  type text not null check (type in (
    'community_comment',
    'community_reply',
    'community_like',
    'squad_comment',
    'squad_reply',
    'squad_like',
    'squad_comment_like',
    'report_resolved',
    'report_dismissed'
  )),
  title text not null,
  body text not null default '',
  href text not null,
  source_key text not null unique,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists user_notifications_user_created_idx
  on public.user_notifications (user_id, created_at desc);
create index if not exists user_notifications_user_unread_idx
  on public.user_notifications (user_id, read_at, created_at desc);

alter table public.user_notifications enable row level security;

revoke all on table public.user_notifications from anon, authenticated;
grant select on table public.user_notifications to authenticated;
grant update (read_at) on table public.user_notifications to authenticated;

drop policy if exists "user_notifications_select_own" on public.user_notifications;
create policy "user_notifications_select_own"
on public.user_notifications for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "user_notifications_update_own" on public.user_notifications;
create policy "user_notifications_update_own"
on public.user_notifications for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create schema if not exists private;

create or replace function private.notify_community_comment()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  recipient uuid;
  actor_name text;
  preview text;
  kind text;
begin
  select coalesce(nullif(p.display_name, ''), '구단주')
    into actor_name
  from public.profiles p
  where p.id = new.user_id;
  actor_name := coalesce(actor_name, '구단주');
  preview := left(regexp_replace(new.content, '[\n\r]+', ' ', 'g'), 100);

  if new.parent_id is not null then
    select c.user_id into recipient
    from public.community_comments c
    where c.id = new.parent_id;
    kind := 'community_reply';
  else
    select p.author_id into recipient
    from public.community_posts p
    where p.id = new.post_id;
    kind := 'community_comment';
  end if;

  if recipient is null or recipient = new.user_id then
    return new;
  end if;

  insert into public.user_notifications (user_id, actor_id, type, title, body, href, source_key)
  values (
    recipient,
    new.user_id,
    kind,
    case when kind = 'community_reply' then '내 댓글에 답글이 달렸어요' else '내 게시글에 댓글이 달렸어요' end,
    actor_name || ' · ' || preview,
    '/community/' || new.post_id::text,
    'community_comment:' || new.id::text
  )
  on conflict (source_key) do nothing;

  return new;
end;
$$;
revoke all on function private.notify_community_comment() from public, anon, authenticated;

drop trigger if exists trg_notify_community_comment on public.community_comments;
create trigger trg_notify_community_comment
after insert on public.community_comments
for each row execute function private.notify_community_comment();

create or replace function private.notify_squad_comment()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  recipient uuid;
  actor_name text;
  preview text;
  kind text;
begin
  select coalesce(nullif(p.display_name, ''), new.author_name, '구단주')
    into actor_name
  from public.profiles p
  where p.id = new.user_id;
  actor_name := coalesce(actor_name, nullif(new.author_name, ''), '구단주');
  preview := left(regexp_replace(new.content, '[\n\r]+', ' ', 'g'), 100);

  if new.parent_id is not null then
    select c.user_id into recipient
    from public.squad_comments c
    where c.id = new.parent_id;
    kind := 'squad_reply';
  else
    select p.author_id into recipient
    from public.squad_posts p
    where p.id = new.post_id;
    kind := 'squad_comment';
  end if;

  if recipient is null or recipient = new.user_id then
    return new;
  end if;

  insert into public.user_notifications (user_id, actor_id, type, title, body, href, source_key)
  values (
    recipient,
    new.user_id,
    kind,
    case when kind = 'squad_reply' then '내 댓글에 답글이 달렸어요' else '내 스쿼드에 댓글이 달렸어요' end,
    actor_name || ' · ' || preview,
    '/squad/gallery/' || new.post_id::text,
    'squad_comment:' || new.id::text
  )
  on conflict (source_key) do nothing;

  return new;
end;
$$;
revoke all on function private.notify_squad_comment() from public, anon, authenticated;

drop trigger if exists trg_notify_squad_comment on public.squad_comments;
create trigger trg_notify_squad_comment
after insert on public.squad_comments
for each row execute function private.notify_squad_comment();

create or replace function private.notify_community_like()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  recipient uuid;
  actor_name text;
  post_title text;
begin
  select p.author_id, p.title into recipient, post_title
  from public.community_posts p
  where p.id = new.post_id;

  if recipient is null or recipient = new.user_id then
    return new;
  end if;

  select coalesce(nullif(p.display_name, ''), '구단주') into actor_name
  from public.profiles p where p.id = new.user_id;
  actor_name := coalesce(actor_name, '구단주');

  insert into public.user_notifications (user_id, actor_id, type, title, body, href, source_key)
  values (
    recipient,
    new.user_id,
    'community_like',
    '내 게시글에 좋아요가 달렸어요',
    actor_name || ' · ' || left(coalesce(post_title, ''), 80),
    '/community/' || new.post_id::text,
    'community_like:' || new.post_id::text || ':' || new.user_id::text
  )
  on conflict (source_key) do nothing;

  return new;
end;
$$;
revoke all on function private.notify_community_like() from public, anon, authenticated;

drop trigger if exists trg_notify_community_like on public.community_likes;
create trigger trg_notify_community_like
after insert on public.community_likes
for each row execute function private.notify_community_like();

create or replace function private.notify_squad_like()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  recipient uuid;
  actor_name text;
  post_title text;
begin
  select p.author_id, p.title into recipient, post_title
  from public.squad_posts p
  where p.id = new.post_id;

  if recipient is null or recipient = new.user_id then
    return new;
  end if;

  select coalesce(nullif(p.display_name, ''), '구단주') into actor_name
  from public.profiles p where p.id = new.user_id;
  actor_name := coalesce(actor_name, '구단주');

  insert into public.user_notifications (user_id, actor_id, type, title, body, href, source_key)
  values (
    recipient,
    new.user_id,
    'squad_like',
    '내 스쿼드에 좋아요가 달렸어요',
    actor_name || ' · ' || left(coalesce(post_title, ''), 80),
    '/squad/gallery/' || new.post_id::text,
    'squad_like:' || new.post_id::text || ':' || new.user_id::text
  )
  on conflict (source_key) do nothing;

  return new;
end;
$$;
revoke all on function private.notify_squad_like() from public, anon, authenticated;

drop trigger if exists trg_notify_squad_like on public.squad_likes;
create trigger trg_notify_squad_like
after insert on public.squad_likes
for each row execute function private.notify_squad_like();

create or replace function private.notify_squad_comment_like()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  recipient uuid;
  post_id uuid;
  actor_name text;
begin
  select c.user_id, c.post_id into recipient, post_id
  from public.squad_comments c
  where c.id = new.comment_id;

  if recipient is null or recipient = new.user_id then
    return new;
  end if;

  select coalesce(nullif(p.display_name, ''), '구단주') into actor_name
  from public.profiles p where p.id = new.user_id;
  actor_name := coalesce(actor_name, '구단주');

  insert into public.user_notifications (user_id, actor_id, type, title, body, href, source_key)
  values (
    recipient,
    new.user_id,
    'squad_comment_like',
    '내 댓글에 좋아요가 달렸어요',
    actor_name || '님이 내 댓글을 좋아합니다.',
    '/squad/gallery/' || post_id::text,
    'squad_comment_like:' || new.comment_id::text || ':' || new.user_id::text
  )
  on conflict (source_key) do nothing;

  return new;
end;
$$;
revoke all on function private.notify_squad_comment_like() from public, anon, authenticated;

drop trigger if exists trg_notify_squad_comment_like on public.squad_comment_likes;
create trigger trg_notify_squad_comment_like
after insert on public.squad_comment_likes
for each row execute function private.notify_squad_comment_like();

create or replace function private.notify_report_status()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  kind text;
  default_body text;
begin
  if new.status is not distinct from old.status then
    return new;
  end if;
  if new.status not in ('resolved', 'dismissed') then
    return new;
  end if;

  if new.status = 'resolved' then
    kind := 'report_resolved';
    default_body := '신고한 내용을 관리자가 처리했습니다.';
  else
    kind := 'report_dismissed';
    default_body := '신고 내용을 검토한 결과 기각되었습니다.';
  end if;

  insert into public.user_notifications (user_id, actor_id, type, title, body, href, source_key)
  values (
    new.reporter_id,
    new.resolved_by,
    kind,
    case when new.status = 'resolved' then '신고가 처리되었습니다' else '신고가 기각되었습니다' end,
    coalesce(nullif(trim(new.resolution_note), ''), default_body),
    '/mypage/reports',
    'report:' || new.id::text || ':' || new.status
  )
  on conflict (source_key) do nothing;

  return new;
end;
$$;
revoke all on function private.notify_report_status() from public, anon, authenticated;

drop trigger if exists trg_notify_report_status on public.content_reports;
create trigger trg_notify_report_status
after update of status on public.content_reports
for each row execute function private.notify_report_status();